### PR TITLE
Version 0.2.1.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by tmatsuo** [comment]
@amyu It's for releasing to pypi.

**Comment by beccasaurus** [comment]
Now that `AsyncPubsubHandler` is recommended, I would suggest updating the README to say ...

> How to use this config file.

``` python
logging.config.fileConfig(os.path.join('examples', 'logging.conf'))
```

And I would rename `examples/async.conf --> examples/logging.conf`, renaming the old `examples/logging.cong` that uses the synchronous `PubsubHandler` to `examples/sync_logging.conf` or something like that.

As a user, when I look in `examples/` I naturally open `logging.conf` because `async.conf` sounds like an edge-case or a more custom configuration.  This way it's obvious that the sync method is the edge-case / more custom configuration.

Maybe point new users to the new recommended practices?

**Comment by beccasaurus** [comment]
Also, the .ini file style configuration document can be syntax highlighted to make it more readable in the README using ````ini`

**Comment by beccasaurus** [comment]
Besides those documentation recommendations, LGTM :thumbsup:

**Comment by tmatsuo** [comment]
Done for config file rename.
For ini, I doubt that works with rst format, but I've uploaded it with the change anyways.

**Comment by tmatsuo** [comment]
All right, now I'm using "ini" syntax highlighting. I'm going to submit this once the travis build is done.

**Comment by tmatsuo** [comment]
@remi Thanks for the review, good catches.
I'm going to release 0.2.1 based on this commit.

Thanks

**Pull request merged**
